### ISSUE TITLE
成功爬取后excel还是只有标题行且无法爬取商品具体信息

### ISSUE THREAD

**Issue by Mir237** [satchmo2000/JD#1]
显示成功爬取，查看excel只有标题行，打印保存函数发现正常，就是无法保存，打印add_product_parameter函数的parameters和para_lists，无反应，该函数无法工作，得到的为空内容。

**Comment by satchmo2000** [comment]
京东有防爬虫的代码，因此这里不要频繁操作，才能看到详细信息。

















在 2024-06-25 15:47:37，"Zhao Shangeng" ***@***.***> 写道：

显示成功爬取，查看excel只有标题行，打印保存函数发现正常，就是无法保存，打印add_product_parameter函数的parameters和para_lists，无反应，该函数无法工作，得到的为空内容。
